# Generated by Django 3.0.3 on 2020-02-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20200214_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='deadline',
        ),
        migrations.AddField(
            model_name='ticket',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Срок'),
        ),
    ]
