# Generated by Django 3.0.3 on 2020-03-16 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0004_auto_20200316_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervision',
            name='supervisors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_in_work', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
    ]
