# Generated by Django 3.0.3 on 2020-03-16 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20200316_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='departament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_tickets', to='tickets.Departament', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='tickets.Attachment'),
        ),
    ]
