# Generated by Django 3.0.5 on 2020-04-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20200323_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.PositiveIntegerField(blank=True, choices=[(100, 'Обычный'), (200, 'Средний'), (300, 'Высокий'), (400, 'Срочный'), (500, 'Критический')], default=100, verbose_name='Приоритет'),
        ),
    ]
