# Generated by Django 3.0.5 on 2020-05-09 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0011_ticket_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='От кого'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(0, 'Новая'), (1, 'Отложена'), (2, 'Отклонена'), (3, 'В работе'), (4, 'Контроль'), (5, 'Завершена')], default=0, verbose_name='Статус'),
        ),
    ]
